source 'https://rubygems.org'

gem 'rails', '4.2'
gem 'sqlite3'

#Gemspec dependencies
gem 'jquery-rails'
gem 'coffee-rails'
gem 'high_voltage'
gem 'sass-rails'
gem 'sprockets'
gem 'es5-shim-rails'
gem 'html5shiv-rails'
gem 'placeholder-gem'
gem 'modernizr-rails'
gem 'pco-url', '>= 1.2.0'
gem 'turbolinks', '~> 2.5.2'
