source 'https://rubygems.org'

gem 'rails', '4.2'
gem 'sqlite3'

#Gemspec dependencies
gem 'jquery-rails'
gem 'coffee-rails'
gem 'sass-rails'
gem 'sprockets'
gem 'turbolinks', '~> 2.5.2'
gem 'autoprefixer-rails', '~> 5.1.11'
gem 'react-rails'
gem 'better_errors'
gem 'binding_of_caller'
